# Generated by Django 2.2 on 2020-05-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresource',
            name='file',
            field=models.FileField(max_length=200, upload_to='courses/resourse/%Y/%m', verbose_name='下载地址'),
        ),
    ]
