# Generated by Django 2.2 on 2020-04-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '课程视频', 'verbose_name_plural': '课程视频'},
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='courses/Course/img/%Y/%m', verbose_name='课程封面图'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='file',
            field=models.FileField(max_length=200, upload_to='courses/CourseResource/resource/%Y/%m', verbose_name='下载地址'),
        ),
    ]
