# Generated by Django 2.2 on 2020-04-28 23:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=100, verbose_name='城市')),
                ('desc', models.CharField(default='', max_length=300, verbose_name='描述')),
            ],
            options={
                'verbose_name': '城市信息',
                'verbose_name_plural': '城市信息',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=50, verbose_name='机构名称')),
                ('tag', models.CharField(default='', max_length=50, verbose_name='机构标签')),
                ('category', models.CharField(default='技术类', max_length=50, verbose_name='机构类别')),
                ('org', models.CharField(choices=[('gr', '个人'), ('gx', '高校')], max_length=10, verbose_name='培训机构')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏数')),
                ('address', models.CharField(max_length=100, verbose_name='机构地址')),
                ('students', models.IntegerField(default=0, verbose_name='学习人数')),
                ('course_nums', models.IntegerField(default=0, verbose_name='课程数')),
                ('is_auth', models.BooleanField(default=False, verbose_name='是否认证')),
                ('is_goldmedal', models.BooleanField(default=False, verbose_name='是否金牌')),
                ('image', models.ImageField(upload_to='organizations/CourseOrg/img/%Y/%m', verbose_name='logo')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.City', verbose_name='所属城市')),
            ],
            options={
                'verbose_name': '教学机构',
                'verbose_name_plural': '教学机构',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=10, verbose_name='教师名')),
                ('word_years', models.IntegerField(default=0, verbose_name='工作年限（单位月）')),
                ('company', models.CharField(default='', max_length=50, verbose_name='就职公司')),
                ('company_position', models.CharField(default='', max_length=50, verbose_name='公司职位')),
                ('teaching_trait', models.CharField(max_length=200, verbose_name='教学特点')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('chick_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏数')),
                ('image', models.ImageField(upload_to='organizations/Teacher/icon/%Y/%m')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.CourseOrg', verbose_name='所属机构')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
            },
        ),
    ]
