# Generated by Django 2.2 on 2020-04-28 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='word_years',
            new_name='work_years',
        ),
    ]
